# docker-compose.yml

version: '3.8'
services:
  node-app:
    container_name: node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - redis
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: true
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: example
  #   depends_on:
  #     - mongo

  redis:
    image: redis

  nginx:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - node-app

  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example

volumes:
  db-data:
  # postgres-db: